### ISSUE TITLE
Profile Detail Page

### ISSUE THREAD

**Issue by claudioccm** [SocialImpactStrategy/people-profiles#1]
Vamos precisar gerar um detail page pra cada profile. Ainda não sei como a página vai ser. 

Olha esse exemplo - http://ghcorps.org/fellows/current-fellows/
Eu acho que o cliente está se inspirando nessa página. 

Podemos fazer esse "detail page" gerando um html pra cada profile, ou fazendo uma modal. Fica a seu critério.

Fiz um layout pro Detail. 
![detail-page](https://cloud.githubusercontent.com/assets/1649373/6371916/3d0d46ee-bcce-11e4-8950-9f9b699cec7c.jpg)
## Hack para gerar um HTML pra cada profile

Esse é o hack que te falei. Só copiei e colei do outro projeto. "coaching-detail-page.html" é o template que gera os html.

```
coaching_class_detail_template = open('%s/coaching-detail-page.html' % searchpath).read()
for index, coaching_class in enumerate(COACHING):
    filename = slugify(coaching_class['name'], to_lower=True)
    f = open("templates/%s-detail.html" % filename, 'w+')
    page_template = coaching_class_detail_template.replace('coaching[0]', 'coaching[%d]' % index)
    f.write(page_template)
    f.close()
```

**Comment by gmattar** [comment]
Já montei toda estrutura HTML, falta o CSS.

**Comment by claudioccm** [comment]
Blz. Se tiver duvida, me avisa

**Comment by gmattar** [comment]
Terminei a tarefa mas não consegui colocar o font-weight certo (300) em alguns pontos. Provavelmente teremos que servir a font-family com essas variacões.
Outra coisa, também não coloquei as aspas na frase abaixo da foto nem os ícones das redes sociais. Preciso das imagens.

**Comment by claudioccm** [comment]
- ![aspas](https://cloud.githubusercontent.com/assets/1649373/6433163/1b06ddc8-c046-11e4-8a5d-b1202cf29bf9.png)
- para os icones eu usei os icones do material, mas eu não consegui incluir eles no push pro repositorio remoto. https://github.com/google/material-design-icons
- para os social - http://fontawesome.io/
- nao precisa esquentar com o font-weight. pode ser 200 ou 400

**Comment by gmattar** [comment]
Coloquei as aspas, falta o font-awesome.
