### ISSUE TITLE
setup do dominio

### ISSUE THREAD

**Issue by claudioccm** [SocialImpactStrategy/people-profiles#7]
dominio vai ser - people.socialimpactstrategy.org
Vamos usar o gh-pages como hsoting.

informação do GoDaddy no seu email (vou mandar assim q eu recebê-las)

**Comment by gmattar** [comment]
Configurei o GoDaddy, mas temos um problema. O site no gh-pages esta dentro de /site/ entao ficou a mesma coisa no outro dominio. people.socialimpactstrategy.org da erro 404, o caminho certo é people.socialimpactstrategy.org/site/

Não consegui melhorar isso no GoDaddy, acho q vamos ter q acertar o gh-pages.

**Comment by claudioccm** [comment]
isso eh facil. basta editar o build.py

**Comment by claudioccm** [comment]
pra gerar os htmls estaticos na root
